LOGDIR: ''
DEVICE: 'cuda'
OUTPUT_DIR: 'results'
NUM_WORKERS: 12
SEED_VALUE: 0
IMG_RES: 256

DATASET:
  LIST: ['coco', 'mpii', 'mpi-inf-3dhp', 'h36m', '3dpw']
  PARTITION: [0.25, 0.05, 0.1, 0.4, 0.2]

LOSS:
  KPT2D: 5.0
  KPT3D: 5.0
  SMPL: 1.0


TRAIN:
  RESUME: None
  LOAD_LATEST: True
  BATCH_SIZE: 64
  LR: 1e-4
  START_EPOCH: 0
  END_EPOCH: 100
  SUMMARY_STEP: 10
  VALID_STEP: 100
  SAVE_STEP: 2000
  MAX_STEP: 80000
  GAMMA: 0.85
  UPDATE_ITER: 5
  CLIP_GRADIENT: True
  CLIP_NORM: 4.0
  MASKED_PROB: 0.25
  WD: 0.0
  OPT: 'Adam'
  

MODEL:
  RADIUS: 3
  POINT_DIM: 1
  LOCAL_DIM: 256
  HIDDEN_DIM: 32
  CORR_LAYER: 2
  REG_LAYER: 1
  BACKBONE: 'hrnet_w48'
  PTYPE: 'marker'
  VERSION: 'refit'

EXP_NAME: 'refit'
COMMENT:
  'Default ReFit configs'


